### ISSUE TITLE
RuntimeError: PythonNext() argument read is not valid: Dynamic cast failed

### ISSUE THREAD

**Issue by ranijames** [google/nucleus#33] opened 2021-01-14 22:58 UTC
Hi All,
Thank you for the tutorial about "Using Nucleus and TensorFlow for DNA Sequencing Error Correction". I am a bioinformatician trying to apply deep learning in genomics. 
As a beginner, I have been trying to run the provided tutorial codes from this [notebook](https://colab.research.google.com/github/google/nucleus/blob/master/nucleus/examples/dna_sequencing_error_correction.ipynb#scrollTo=4Skgb4NFvavF)

However, in the final step, it is throwing the error as follows,
```
hparams = BaseHparams()
run(hparams)
```

The error,

```
Generating data...
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-12-d46fc6eb10e4> in <module>
      1 # This cell should take ~6 minutes to run with the default parameters.
      2 hparams = BaseHparams()
----> 3 run(hparams)

<ipython-input-11-eb89d5445b01> in run(hparams, use_existing_data, seed)
      9   if not use_existing_data:
     10     print('Generating data...')
---> 11     generate_tfrecord_datasets(hparams)
     12 
     13   train_dataset = get_dataset(

<ipython-input-5-25c33ad9027c> in generate_tfrecord_datasets(hparams)
     15        TFRecordWriter(os.path.join(hparams.out_dir, _TEST)) as test_out:
     16     all_examples = make_ngs_examples(hparams)
---> 17     for example in all_examples:
     18       r = random.random()
     19       if r < train_eval_test_split[0]:

<ipython-input-5-25c33ad9027c> in make_ngs_examples(hparams)
     44   used_pileup_ranges = set()
     45   with ref_reader, vcf_reader, sam_reader, sam_query_reader:
---> 46     for read in sam_reader:
     47 
     48       # Check that read has cigar string present and allowed alignment.

~/anaconda3/envs/tensorflow/lib/python3.7/site-packages/nucleus/io/clif_postproc.py in __next__(self)
     65   def __next__(self):
     66     try:
---> 67       record, not_done = self._raw_next()
     68     except AttributeError:
     69       if self._cc_iterable is None:

~/anaconda3/envs/tensorflow/lib/python3.7/site-packages/nucleus/io/clif_postproc.py in _raw_next(self)
    124   def _raw_next(self):
    125     record = reads_pb2.Read()
--> 126     not_done = self._cc_iterable.PythonNext(record)
    127     return record, not_done
    128 

RuntimeError: PythonNext() argument read is not valid: Dynamic cast failed
```
The versions of neccesary packages are, 
```protobuf               3.14.0

google-nucleus         0.5.6
tensorflow             2.2.0
tensorflow-estimator   2.2.0
tensorflow-gpu         2.2.0
protobuf               3.14.0

```
 It is not clear, what is going wrong here. I am using the most recent version of all packages.
 I am running all these on `Ubuntu 18.04.5 LTS`, and in a separate virtual environment.
Any help or suggestion is greatly appreciated!
Thanks

**Comment by gunjanbaid** [comment] 2021-01-15 00:06
@ranijames v0.5.6 of Nucleus requires TF 2.3.0. Could you try running the notebook with TF 2.3.0?

**Comment by ranijames** [comment] 2021-01-16 11:27
@gunjanbaid Thanks for the reply. I have created a new environment with TF 2.3.0. And tried to run the code in the notebook. Now, when I try to import all the modules new error,
```
TypeError                                 Traceback (most recent call last)
<ipython-input-3-36045406c016> in <module>
      8 import numpy as np
      9 
---> 10 from nucleus.io import fasta
     11 from nucleus.io import sam
     12 from nucleus.io import vcf

~/anaconda3/envs/nucleus/lib/python3.8/site-packages/nucleus/io/fasta.py in <module>
     45 from nucleus.io import genomics_reader
     46 from nucleus.io.python import reference
---> 47 from nucleus.protos import fasta_pb2
     48 from nucleus.protos import reference_pb2
     49 from nucleus.util import ranges

~/anaconda3/envs/nucleus/lib/python3.8/site-packages/nucleus/protos/fasta_pb2.py in <module>
     14 
     15 
---> 16 from nucleus.protos import range_pb2 as nucleus_dot_protos_dot_range__pb2
     17 from nucleus.protos import reference_pb2 as nucleus_dot_protos_dot_reference__pb2
     18 

~/anaconda3/envs/nucleus/lib/python3.8/site-packages/nucleus/protos/range_pb2.py in <module>
     34   containing_type=None,
     35   fields=[
---> 36     _descriptor.FieldDescriptor(
     37       name='reference_name', full_name='nucleus.genomics.v1.Range.reference_name', index=0,
     38       number=1, type=9, cpp_type=9, label=1,

~/anaconda3/envs/nucleus/lib/python3.8/site-packages/google/protobuf/descriptor.py in __new__(cls, name, full_name, index, number, type, cpp_type, label, default_value, message_type, enum_type, containing_type, is_extension, extension_scope, options, serialized_options, has_default_value, containing_oneof, json_name, file)
    528                 has_default_value=True, containing_oneof=None, json_name=None,
    529                 file=None):  # pylint: disable=redefined-builtin
--> 530       _message.Message._CheckCalledFromGeneratedFile()
    531       if is_extension:
    532         return _message.default_pool.FindExtensionByName(full_name)

TypeError: Descriptors should not be created directly, but only retrieved from their parent.

```
Looking forward to your answer! Thanks

**Comment by gunjanbaid** [comment] 2021-01-19 16:50
@ranijames We have seen this issue caused by having an incompatible protobuf version. In addition to having Nucleus at 0.5.6 and TF at 2.3.0, you should not install protobuf directly beforehand (or if you do, pin it to 3.9.2).

**Comment by gunjanbaid** [comment] 2021-02-22 05:13
Closing this issue out, but feel free to reopen if you have any other questions @ranijames!

**Closed by gunjanbaid** 2021-02-22 05:13 UTC
